### ISSUE TITLE
TBS6680 support possible?

### ISSUE THREAD

**Issue by hrodenburg** [ljalves/linux_media#11] opened 2014-01-04 16:18 UTC
Hello Luis,

I've currently switched to your driver for my TBS6981. I really appreciate your work on this! In the same pc I have an TBS6680 DVB-C card. This card has an SAA7160 chipset, just like the TBS6984 (which is in my production tv system at the moment, running the TBS drivers). At this moment I am unable to use the 6680 since I'm not using TBS's drivers anymore.
Is is possible to use your drivers for the TBS6680 too, since it uses the same chipset as the TBS6984? Or is there a lot of work needed to get this working? As this is beyond my level of expertise, I'm not sure how many work needs to be done for this.
Offcourse I will be more than happy to supply any information needed or to do some testing if needed.

Thanks in advance.

lspci output of the TBS6680
07:00.0 Multimedia controller: Philips Semiconductors SAA7160 (rev 03)
        Subsystem: Device 6680:0001
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 16 bytes
        Interrupt: pin A routed to IRQ 11
        Region 0: Memory at fea00000 (64-bit, non-prefetchable) [size=1M]
        Capabilities: [40] MSI: Enable- Count=1/32 Maskable- 64bit+
                Address: 0000000000000000  Data: 0000
        Capabilities: [50] Express (v1) Endpoint, MSI 00
                DevCap: MaxPayload 128 bytes, PhantFunc 0, Latency L0s <256ns, L1 <1us
                        ExtTag- AttnBtn- AttnInd- PwrInd- RBE- FLReset-
                DevCtl: Report errors: Correctable- Non-Fatal- Fatal- Unsupported-
                        RlxdOrd+ ExtTag- PhantFunc- AuxPwr- NoSnoop-
                        MaxPayload 128 bytes, MaxReadReq 128 bytes
                DevSta: CorrErr- UncorrErr+ FatalErr- UnsuppReq+ AuxPwr- TransPend-
                LnkCap: Port #1, Speed 2.5GT/s, Width x1, ASPM L0s L1, Latency L0 <4us, L1 <64us
                        ClockPM- Surprise- LLActRep- BwNot-
                LnkCtl: ASPM Disabled; RCB 128 bytes Disabled- Retrain- CommClk-
                        ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed 2.5GT/s, Width x1, TrErr- Train- SlotClk- DLActive- BWMgmt- ABWMgmt-
        Capabilities: [74] Power Management version 2
                Flags: PMEClk- DSI- D1+ D2+ AuxCurrent=0mA PME(D0+,D1+,D2+,D3hot-,D3cold-)
                Status: D0 NoSoftRst- PME-Enable- DSel=0 DScale=0 PME-
        Capabilities: [80] Vendor Specific Information: Len=50 <?>
        Capabilities: [100 v0] #41ed

**Comment by danielhitch** [comment] 2015-01-26 22:14
Hi.

Sorry to bring up an old thread - Has there been any progress on this??

I could probably stomach the price of a TBS6618 card - Not sure of hardware specs but guessing the TBS6680 is just a twin version to the TBS6618??

If somebody could confirm my suspicions and ljalves could devote some time to adding DVB-C drivers to the cause, I would be happy to help!!

**Comment by danielhitch** [comment] 2015-01-27 15:57
Hi Hugo,

I tried finding your email address but you have it hidden in your profile - I am hoping you are still subscribed to this post, and can assist Luis and myself in finding some specs on the TBS6680.

I currently do not have one of these cards but am extremely interested in purchasing one (when a stable Linux driver is available for it).

Would it be possible to send me some extremely high resolution pictures of the chips on the card (chip numbers would need to be visible), so that I can assist Luis in getting details together for this card.

The spec that you posted above from LinuxTV is for the TBS6618 and whilst I think that the TBS6680 is just a twin version of that card, I need to make sure before making the purchase of the TBS6618 card to donate to Luis for the development of hopefully the TBS6618, TBS6680 and TBS5680 (which all on the face of it, appear as if they may share the same hardware).

I have enabled my email address in my profile so, please get in touch (or reply on here).

Dan

**Comment by dahlSTROM** [comment] 2015-01-29 19:21
Here are some pictures:

![dsc04580](https://cloud.githubusercontent.com/assets/1389407/5964259/0b169d24-a7f3-11e4-90b7-372f1df73ed0.JPG)

![dsc04581](https://cloud.githubusercontent.com/assets/1389407/5964269/1f818404-a7f3-11e4-97f4-2a3de9f0c16b.JPG)

![dsc04578](https://cloud.githubusercontent.com/assets/1389407/5964400/0e861330-a7f4-11e4-9f8f-cfd37ac8c78f.JPG)


![dsc04576](https://cloud.githubusercontent.com/assets/1389407/5964306/6f96cd5a-a7f3-11e4-9ad7-daec7212accd.JPG)

![dsc04573](https://cloud.githubusercontent.com/assets/1389407/5964323/87444ed2-a7f3-11e4-9742-2a60e2256693.JPG)

Please tell me if you need more info/help. It sure would have been nice with open source drivers available for the TBS 6680. :)

**Comment by ljalves** [comment] 2015-01-30 11:37
I would say that this cards should be easy to add.
From this patch (https://patchwork.linuxtv.org/patch/7499/) the tda10023 should work.

I'll take a look into this when I find the time.

**Comment by dahlSTROM** [comment] 2015-01-30 13:23
That's great news. Do you also know if CI support and IR is going to work? They are open source (dahlSTROM/tbs6680-intree@8dd1fdb9e7519ce9ab3d379475e10f2dad7a68df and dahlSTROM/tbs6680-intree@d8d23705f711d9587cbc83f4973a4ee8046ffc3f) but I'm not sure what's needed to get it working.

**Comment by ljalves** [comment] 2015-05-02 19:33
I've been lacking time for developing/adding drivers for new cards.
Lately I barely have time to keep the tree updated with the latest official media tree.

**Comment by ljalves** [comment] 2016-06-24 16:32
Not adding this driver (got no card to test).
Closing - reopen if needed.

**Closed by ljalves** 2016-06-24 16:32 UTC
Labels: enhancement
