### ISSUE TITLE
Compile for Raspbian (Debian Wheezy) 

### ISSUE THREAD

**Issue by saeedmou** [ljalves/linux_media#51] opened 2014-11-27 15:57 UTC
i`ve a Raspberry Pi B+ board (arm arch) with Linux Raspbian (Debian Wheezy) kernel 3.12.28+.

more info :http://www.raspberrypi.org/

my dvb is TBS qbox 5922 usb.
i installed a fresh Raspbian on my board, but i can`t compile the driver, i just type this:

Linux raspberrypi 3.12.28+ #709 PREEMPT Mon Sep 8 15:28:00 BST 2014 armv6l
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Nov 27 12:37:12 2014 from 192.168.1.101

pi@raspberrypi ~ $ git clone git://linuxtv.org/media_build.git

Cloning into 'media_build'...
remote: Counting objects: 2592, done.
remote: Compressing objects: 100% (975/975), done.
remote: Total 2592 (delta 1812), reused 2261 (delta 1577)
Receiving objects: 100% (2592/2592), 516.33 KiB | 113 KiB/s, done.
Resolving deltas: 100% (1812/1812), done.

pi@raspberrypi ~ $ git clone --depth=1 https://github.com/ljalves/linux_media.git -b latest ./media

Cloning into './media'...
remote: Counting objects: 100542, done.
remote: Compressing objects: 100% (87835/87835), done.
remote: Total 100542 (delta 48015), reused 35118 (delta 11786)
Receiving objects: 100% (100542/100542), 156.74 MiB | 73 KiB/s, done.
Resolving deltas: 100% (48015/48015), done.
Checking out files: 100% (48069/48069), done.

pi@raspberrypi ~ $ cd media_build
pi@raspberrypi ~/media_build $ make dir DIR=../media

make -C linux/ dir DIR="../../media"
make[1]: Entering directory '/home/pi/media_build/linux'
rm -rf drivers firmware include sound .patches_applied .linked_dir .git_log.md5 git_log kernel_version.h
/bin/sh: 1: lsdiff: not found
Makefile:119: recipe for target 'dir' failed
make[1]: *** [dir] Error 127
make[1]: Leaving directory '/home/pi/media_build/linux'
Makefile:32: recipe for target 'dir' failed
make: *** [dir] Error 2

is there any Requrirements ?!
and i`m new with linux...

**Comment by ljalves** [comment] 2015-01-15 15:33
@saeedmou 
Did you solve your issues?

**Comment by saeedmou** [comment] 2015-01-16 18:24
@ljalves 
1. yes build process completed without error.
2.yes i used  "sudo make install"

the building process is too heavy for raspberrypi, about 12H.
now i`m busy with my thesis, i`ll try in 2 or 3 month. i`wont give up!! NEVER!

**Comment by ljalves** [comment] 2015-01-28 15:15
Closing and marking this as duplicate of #55
Comment there your progress whenever you try again.

**Closed by ljalves** 2015-01-28 15:15 UTC
Labels: duplicate, question
